---
- name: Check nps-hmg
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Check status autoscaling
      shell: aws autoscaling describe-auto-scaling-instances | grep LifecycleState
      register: lifecyclestate
    - debug:
        var: lifecyclestate

    - name: Check status target group
      shell: aws elbv2 describe-target-health --target-group-arn arn:aws:elasticloadbalancing:us-east-1:843734137748:targetgroup/track-nps-hmg/cc8ae322cd5b575b | grep State
      register: state
    - debug:
        var: state

    - name: Check status codedeploy
      shell: aws codepipeline get-pipeline-state --name track-nps-hmg | grep status
      register: status
    - debug:
        var: status

    - name: Curl tracksale.info
      shell: curl -G https://tracksale.info/login
      register: curl
    - debug:
        var: curl
