---
- name: Check nps-hmg
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Check status autoscaling
      shell: sudo /usr/local/bin/aws autoscaling describe-auto-scaling-instances | grep -i 'LifecycleState'

    - name: Check status target group
      shell: sudo /usr/local/bin/aws elbv2 describe-target-health --target-group-arn arn:aws:elasticloadbalancing:us-east-1:843734137748:targetgroup/track-nps-hmg/cc8ae322cd5b575b | grep -i 'State'

    - name: Check status codedeploy
      shell: sudo /usr/local/bin/aws codepipeline get-pipeline-state --name track-nps-hmg | grep -i 'status'

    - name: Curl tracksale.info
      shell: curl -G https://tracksale.info/login
      register: curl
    - debug:
        var: curl
