{
 "title": "Docker cAdvisor container dashboard for AWS ECS",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total, job)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{job=\"$job\"}, container_label_com_amazonaws_ecs_cluster)"
    }
   },
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{job=\"$job\",container_label_com_amazonaws_ecs_cluster=\"$cluster\",from=\"docker\"}, name)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{name=~\"$name\",container_label_com_amazonaws_ecs_cluster=\"$cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node list",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(container_last_seen{name=~\"$name\",container_label_com_amazonaws_ecs_cluster=~\"$cluster\",instance=~\"$instance\",image!=\"\"}) by (instance)"
    },
    {
     "expr": "sum(machine_cpu_cores{name=~\"$name\",container_label_com_amazonaws_ecs_cluster=~\"$cluster\",instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "sum(irate(container_cpu_user_seconds_total{name=~\"$name\",container_label_com_amazonaws_ecs_cluster=~\"$cluster\",instance=~\"$instance\",image!=\"\"}[5m]) * 100) by (instance) / sum(machine_cpu_cores{instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "((sum(container_memory_usage_bytes{name=~\"$name\",container_label_com_amazonaws_ecs_cluster=~\"$cluster\",instance=~\"$instance\",image!=\"\"}) by (instance) - sum(container_memory_cache{name=~\"$name\",container_label_com_amazonaws_ecs_cluster=~\"$cluster\",instance=~\"$instance\",image!=\"\"}) by (instance)) / sum(machine_memory_bytes{instance=~\"$instance\"}) by (instance)) * 100"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name=~\"$name\",container_label_com_amazonaws_ecs_cluster=~\"$cluster\",instance=~\"$instance\",image!=\"\"}) by (instance) - sum(container_memory_cache{name=~\"$name\",container_label_com_amazonaws_ecs_cluster=~\"$cluster\",instance=~\"$instance\",image!=\"\"}) by (instance)"
    },
    {
     "expr": "sum(machine_memory_bytes{instance=~\"$instance\",container_label_com_amazonaws_ecs_cluster=~\"$cluster\"}) by (instance)"
    },
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{name=~\"$name\",instance=~\"$instance\",container_label_com_amazonaws_ecs_cluster=~\"$cluster\",image!=\"\"}[5m])) by (instance)"
    },
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{name=~\"$name\",instance=~\"$instance\",container_label_com_amazonaws_ecs_cluster=~\"$cluster\"}[5m])) by (instance)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{name=~\"$name\",instance=~\"$instance\",container_label_com_amazonaws_ecs_cluster=~\"$cluster\"}[5m])) by (instance)"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{name=~\"$name\",instance=~\"$instance\",container_label_com_amazonaws_ecs_cluster=~\"$cluster\"}[5m])) by (instance)"
    }
   ]
  },
  { "title": "$name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Usage:sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum without (dc,from,id) (irate(container_cpu_user_seconds_total{name=~\"$name\",container_label_com_amazonaws_ecs_cluster=~\"$cluster\",instance=~\"$instance\",image!=\"\"}[5m]) * 100)",
     "legendFormat": "{{name}}: {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage:sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without (dc,from,id) (container_memory_usage_bytes{name=~\"$name\",container_label_com_amazonaws_ecs_cluster=~\"$cluster\",instance=~\"$instance\",image!=\"\"} - container_memory_cache{name=~\"$name\",container_label_com_amazonaws_ecs_cluster=~\"$cluster\",instance=~\"$instance\",image!=\"\"})",
     "legendFormat": "{{name}}: {{instance}}"
    }
   ]
  },
  {
   "title": "I/O Tx:sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without (dc,from,id) (irate(container_fs_writes_bytes_total{name=~\"$name\",container_label_com_amazonaws_ecs_cluster=~\"$cluster\",instance=~\"$instance\",image!=\"\",device!~\"/dev/dm.*\"}[5m]))",
     "legendFormat": "{{name}}: device=\"{{device}}\", instance=\"{{instance}}\""
    }
   ]
  },
  {
   "title": "I/O Rx:sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without (dc,from,id) (irate(container_fs_reads_bytes_total{name=~\"$name\",container_label_com_amazonaws_ecs_cluster=~\"$cluster\",instance=~\"$instance\",image!=\"\",device!~\"/dev/dm.*\"}[5m]))",
     "legendFormat": "{{name}}: device=\"{{device}}\", instance=\"{{instance}}\""
    }
   ]
  },
  {
   "title": "Network Tx:sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without (dc,from,id) (irate(container_network_transmit_bytes_total{name=~\"$name\", container_label_com_amazonaws_ecs_cluster=~\"$cluster\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{name}}: {{instance}}"
    }
   ]
  },
  {
   "title": "Network Rx:sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without (dc,from,id) (irate(container_network_receive_bytes_total{name=~\"$name\",instance=~\"$instance\",container_label_com_amazonaws_ecs_cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "{{name}}: {{instance}}"
    }
   ]
  }
 ]
}