global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

#remote_write:
  #- url: "http://localhost:8086/api/v1/prom/write?db=prometheus&u=admin&p=Ob9jupho"

#remote_read:
  #- url: "http://localhost:8086/api/v1/prom/read?db=prometheus&u=admin&p=Ob9jupho"
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
        labels:
          instance: 'app01'
  - job_name: 'node-exporter' 
    static_configs: 
      - targets: ['node-exporter:9100']
        labels:
          instance: 'app01'
  - job_name: 'cAdvisor' 
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          instance: 'app01'
  - job_name: 'grafana'
    scrape_interval: 15s
    scrape_timeout: 5s
    static_configs:
      - targets: ['host.docker.internal:3000']
  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['host.docker.internal:9104']
        labels:
          instance: 'app01'
  - job_name: blackbox_http
    metrics_path: /probe
    params:
      module:
      - http_2xx
    relabel_configs:
    - source_labels:
      - __address__
      target_label: __param_target
    - source_labels:
      - __param_target
      target_label: instance
    - replacement: host.docker.internal:9115	
      target_label: __address__
    static_configs:
    - targets:
      - http://node-exporter:9100/metrics
      - http://host.docker.internal:3000/metrics
      - http://cadvisor:8080/metrics
  - job_name: blackbox_https
    scrape_timeout: 15s
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
    - targets:
      - https://robertasoliman.tech/
      - https://www.fibonaccit.com/
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: host.docker.internal:9115