global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

#remote_write:
  #- url: "http://localhost:8086/api/v1/prom/write?db=prometheus&u=admin&p=Ob9jupho"

#remote_read:
  #- url: "http://localhost:8086/api/v1/prom/read?db=prometheus&u=admin&p=Ob9jupho"
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['34.203.203.38:9090']
  - job_name: 'node-exporter-jenkins' 
    static_configs: 
      - targets: ['3.84.92.59:9101']
        labels:
          instance: 'jenkins'
  - job_name: 'cAdvisor-jenkins' 
    static_configs:
      - targets: ['3.84.92.59:8085']
        labels:
          instance: 'jenkins'

  - job_name: 'node-exporter-backend' 
    static_configs: 
      - targets: ['3.87.67.0:9101']
        labels:
          instance: 'backend'
  - job_name: 'cAdvisor-backend' 
    static_configs:
      - targets: ['3.87.67.0:8085']
        labels:
          instance: 'backend'

  - job_name: 'node-exporter-frontend' 
    static_configs: 
      - targets: ['3.82.243.236:9101']
        labels:
          instance: 'frontend'
  - job_name: 'cAdvisor-frontend' 
    static_configs:
      - targets: ['3.82.243.236:8085']
        labels:
          instance: 'frontend'

  - job_name: 'node-exporter-ELK' 
    static_configs: 
      - targets: ['52.90.196.49:9101']
        labels:
          instance: 'ELK'
  - job_name: 'cAdvisor-ELK' 
    static_configs:
      - targets: ['52.90.196.49:8085']
        labels:
          instance: 'ELK'

  - job_name: 'node-exporter-dev' 
    static_configs: 
      - targets: ['34.239.106.204:9101']
        labels:
          instance: 'DevOps'
  - job_name: 'cAdvisor-dev' 
    static_configs:
      - targets: ['34.239.106.204:8085']
        labels:
          instance: 'DevOps'


  - job_name: 'grafana'
    scrape_interval: 15s
    scrape_timeout: 5s
    static_configs:
      - targets: ['34.203.203.38:3005']
  - job_name: blackbox_http
    metrics_path: /probe
    params:
      module:
      - http_2xx
    relabel_configs:
    - source_labels:
      - __address__
      target_label: __param_target
    - source_labels:
      - __param_target
      target_label: instance
    - replacement: 34.203.203.38:9115	
      target_label: __address__
    static_configs:
    - targets:
      - http://3.87.67.0:4000/
  - job_name: blackbox_https
    scrape_timeout: 15s
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
    - targets:
      - https://robertasoliman.tech/
      - https://www.fibonaccit.com/
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 34.203.203.38:9115	
  - job_name: 'jenkins'
    metrics_path: /prometheus
    scheme: http
    static_configs:
      - targets: ['34.203.203.38:9999']